server:
  port: 12000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-search
  redis:
    host: 192.168.13.131
  session:
    store-type: redis