server:
  port: 40000

spring:
  application:
    name: gulimall-cart-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.13.131

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10