spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.13.131:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-ware
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  rabbitmq:
    host: 192.168.13.131
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual #手动ack模式


mybatis-plus:
  global-config:
    db-config:
      id-type: auto #设置所有主键生成规则 和entity 上的注解@TableId【标识主键】 搭配使用
  mapper-locations: classpath:/mapper/**/*.xml #classpath* 不止扫描自己的类路径引用的其他jar包的类路径都扫描



server:
  port: 11000
logging:
  level:
    com.cqm.gulimall: debug
